FROM node:16.13-alpine as build

WORKDIR /app

COPY ./client .
RUN npm ci
RUN npm run build

FROM node:16.13-alpine

WORKDIR /client

COPY --from=build /app/build ./build
RUN npm i -g serve

EXPOSE 5000
CMD ["serve", "-s", "build", "-p", "5000"]
