module.exports = [
    [
        {
            nAns: 1,
            content: [" is the most arousing thing in the world."],
            begin: true
        },
        {
            nAns: 2,
            content: ["When I'm at ", " all alone, I like ", "."],
            begin: false
        },
        {
            nAns: 1,
            content: ["Hey Reddit! I’m ", ". Ask me anything."],
            begin: false
        },
        {
            nAns: 2,
            content: ["That’s right, I killed ", ". How, you ask? ","."],
            begin: false
        },
        {
            nAns: 1,
            content: ["I’m sorry, Professor, but I couldn’t complete my homework because of ", "."],
            begin: false
        },
        {
            nAns: 2,
            content: ["And the Academy Award for ", " goes to ", "."],
            begin: false
        },
        {
            nAns: 1,
            content: ["Dude, do not go in that bathroom. There’s ", " in there."],
            begin: false
        },
        {
            nAns: 1,
            content: ["How did I lose my virginity?"],
            begin: false
        },
        {
            nAns: 2,
            content: ["Step 1: ", ". Step 2: ", ". Step 3: Profit."],
            begin: false
        },
        {
            nAns: 1,
            content: [".Betcha can’t have just one!"],
            begin: true
        },
        {
            nAns: 1,
            content: ["When I am President,I will create the Department of ", "."],
            begin: false
        },
        
    ],
    [
        {content: "Yo mamma"},
        {content: "Richard Gere holding a banana"},
        {content: "A very clever monkey"},
        {content: "Some ugly sweater"},
        {content: "My father's penis"},
        {content: "Venereal Desease"},
        {content: "A bunch of sweaty men"},
        {content: "A fully charged phone"},
        {content: "A very hairy pizza delivery guy"},
        {content: "Silence"},
        {content: "The illusion of choice ina late-stage capitalist society"},
        {content: "Many bats"},
        {content: "Famine"},
        {content: "Flesh-eating bacteria"},
        {content: "Flying sex snakes"},
        {content: "Not giving ashit about theThird World"},
        {content: "Magnets"},
        {content: "Shapeshifters"},
        {content: "Seeing what happens when you lock people in a room with hungry seagulls"},
        {content: "A crucifixion"},
        {content: "Jennifer Lawrence"},
        {content: "72 virgins"},
        {content: "A live studio audience"},
        {content: "A time travel paradox."},
        {content: "Authentic Mexican cuisine"},
        {content: "Doing crimes"},
        {content: "Synergistic management solutions"},
        {content: "Crippling debt"},
        {content: "Daddy issues"},
        {content: "Used panties"},
        {content: "A fart so powerful that it wakes the giants from their thousand-year slumber."},
        {content: "Former President George W. Bush"},
        {content: "Full frontal nudity"},
        {content: "Covering myself with Parmesan cheese and chili flakes becauseI am pizza"},
        {content: "Laying an egg"},
        {content: "Getting naked and watching Nickelodeon"},
        {content: "Having big dreams but no realistic way to achieve them"},
        {content: "Seeing Grandma naked"},
        {content: "Boogers"},
        {content: "The inevitable heat death ofthe universe"},
        {content: "The miracleof childbirth"},
        {content: "The Rapture"},
        {content: "Whipping it out"},
        {content: "White privilege"},
        {content: "Emerging from the sea and rampaging through Tokyo"},
        {content: "The Bloodof Christ"},
        {content: "Soft, kissy missionary sex"},
        {content: "BATMAN!"},
        {content: "Agriculture"},
        {content: "Barely making $25,000 a year"},
        {content: "Natural selection"},
        {content: "Coat hanger abortions"},
        {content: "Sex withPatrick Stewart"},
        {content: "My abusive boyfriend who really isn’t so bad once you get to know him"},
        {content: "Prescriptionpain killers"},
        {content: "Swooping"},
        {content: "Mansplaining"},
        {content: "A homoerotic volleyball montage"},
        {content: "Alexandria Ocasio-Cortez"},
        {content: "Putting things where they go"},
        {content: "Fragile masculinity"},
        {content: "All-you-can-eat shrimp for $8.99"},
        {content: "An old guy who’s almost dead"},
        {content: "Kanye West"},
        {content: "Hot cheese"},
        {content: "Seven dead and three in critical condition"},
        {content: "Raptor attacks"},
        {content: "Smegma"},
        {content: "Alcoholism"},
        {content: "A middle-aged man on roller skates"},
        {content: "Looking in the mirror, applying lipstick, and whispering “tonight, you will have sex with Tom Cruise.”"},
        {content: "Bingeing and purging"},
        {content: "An oversized lollipop"},
        {content: "Self-loathing"},
        {content: "Sitting on my face and telling me I’m garbage"},
        {content: "Half-assed foreplay"},
        {content: "The Holy Bible"},
        {content: "German dungeon porn"},
        {content: "Being on fire"},
        {content: "Teenage pregnancy"},
        {content: "Gandhi"},
        {content: "Your weird brother"},
        {content: "A Fleshlight"},
        {content: "A pyramid of severed heads"},
        {content: "An erection that lasts longer than four hours"},
        {content: "A three-way with my wife and Shaquille O’Nea"},
    ]
];